local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.DIVING_BELL = "Diving Bell"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DIVING_BELL = "Refill your lungs"

STRINGS.NAMES.ANCHOR_EXIT = "Anchor"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DIVING_BELL = "Return to the surface"

STRINGS.NAMES.SMALL_CRATE = "Crate"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SMALL_CRATE = "What can it have inside ?"

STRINGS.NAMES.MEDIUM_CRATE = "Crate"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MEDIUM_CRATE = "What can it have inside ?"

STRINGS.NAMES.BIG_CRATE = "Crate"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BIG_CRATE = "What can it have inside ?"

STRINGS.NAMES.CRAB = "Crabbit"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRAB = "A little crab, how adorable"

STRINGS.NAMES.CRABHOLE = "Crabbit's den"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRABHOLE = "It's the den of a mighty creature !"

STRINGS.NAMES.CORAL = "Coral"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL = "So tiny yet so beautifull"

STRINGS.NAMES.CORAL_SHARD = "Coral shard"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL_SHARD = "It's verry sturdy !"

STRINGS.NAMES.SEAWEED = "Seaweed"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED = "An aquatic tree ?"

STRINGS.NAMES.BULB_KELP = "Kelp's bulb"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULB_KELP = "Is it tasty ?"

STRINGS.NAMES.DROWNED = "Drowned"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DROWNED = "Will I end like him ?"