local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.DIVING_BELL = "Diving Bell"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DIVING_BELL = "Refill your lungs"

STRINGS.NAMES.ANCHOR_EXIT = "Anchor"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DIVING_BELL = "Return to the surface"